[build]
  publish = "."

# Enable Pretty URLs
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Force non-www â†’ apex domain
[[redirects]]
  from = "https://www.ankushinfotech.com/*"
  to = "https://ankushinfotech.com/:splat"
  status = 301
  force = true
