[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Force non-www
[[redirects]]
  from = "https://www.ankushinfotech.com/*"
  to = "https://ankushinfotech.com/:splat"
  status = 301
  force = true

# Short URL Fixes
[[redirects]]
  from = "/hireappdeve"
  to = "/freelance-mobile-application-development"
  status = 301

[[redirects]]
  from = "/hireseo"
  to = "/hire-freelance-seo-services"
  status = 301

[[redirects]]
  from = "/hiresoftwarede"
  to = "/hire-freelance-software-development-in-mumbai"
  status = 301

[[redirects]]
  from = "/hireuiuxdeve"
  to = "/hire-ui-ux-web-design-website-developer-in-maharastra"
  status = 301

[[redirects]]
  from = "/hirewebsite"
  to = "/hire-freelance-website-development-navi-mumbai"
  status = 301

[[redirects]]
  from = "/digitalmarket"
  to = "/freelancer-digital-marketing"
  status = 301

[[redirects]]
  from = "/pages/about"
  to = "/about"
  status = 301

[[redirects]]
  from = "/pages/contact"
  to = "/contact"
  status = 301

# 404 (ALWAYS LAST)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
