[[redirects]]
  from = "http://ankushinfotech.com/*"
  to = "https://www.ankushinfotech.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ankushinfotech.com/*"
  to = "https://www.ankushinfotech.com/:splat"
  status = 301
  force = true
